SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_Machine_Process_AlertConfiguration_View] AS SELECT[config].[Cluster_Machine_Process_AlertConfiguration].[Id] AS [Id], [config].[Cluster_Machine_Process_AlertConfiguration].[_AlertType] AS [Cluster_Machine_Process_AlertType], [config].[Cluster_Machine_Process_AlertConfiguration].[_SubType] AS [Cluster_Machine_Process_SubType], [config].[Cluster_Machine_Process_AlertConfiguration].[_Configuration] AS [Cluster_Machine_Process_Configuration], [config].[Cluster_Machine_Process_AlertConfiguration].[_Enabled] AS [Cluster_Machine_Process_Enabled], [config].[Cluster_Machine_Process_AlertConfiguration].[_AlertNotification] AS [Cluster_Machine_Process_AlertNotification], [config].[Cluster_Machine_Process_AlertConfiguration].[_EmailAddress] AS [Cluster_Machine_Process_EmailAddress], [config].[Cluster_Machine_Process_AlertConfiguration].[_Version] AS [Cluster_Machine_Process_Version], [config].[Cluster_Machine_Process_AlertConfiguration].[_Comments] AS [Cluster_Machine_Process_Comments], [config].[Cluster_Machine_Process_AlertConfiguration].[_SlackEnabled] AS [Cluster_Machine_Process_SlackEnabled], [config].[Cluster_Machine_Process_AlertConfiguration].[_SnmpEnabled] AS [Cluster_Machine_Process_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_Machine_Keys].[_Name] AS [Cluster_Machine_Name], [data].[Cluster_Machine_Process_Keys].[_Id] AS [Cluster_Machine_Process_Id], [data].[Cluster_Machine_Process_Keys].[_StartDate] AS [Cluster_Machine_Process_StartDate], [utils].[TicksToDateTime]([data].[Cluster_Machine_Process_Keys].[_StartDate]) AS [Cluster_Machine_Process_StartDate_DateTime] FROM [config].[Cluster_Machine_Process_AlertConfiguration] INNER JOIN [data].[Cluster_Machine_Process_Keys] ON [data].[Cluster_Machine_Process_Keys].[Id] = [config].[Cluster_Machine_Process_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_Machine_Keys] ON [data].[Cluster_Machine_Keys].[Id] = [data].[Cluster_Machine_Process_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_Machine_Keys].[ParentId]
;
GO
