SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[AzureSqlServer_Database_Waits_AlertConfiguration_View] AS SELECT[config].[AzureSqlServer_Database_Waits_AlertConfiguration].[Id] AS [Id], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_AlertType] AS [AzureSqlServer_Database_Waits_AlertType], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_SubType] AS [AzureSqlServer_Database_Waits_SubType], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_Configuration] AS [AzureSqlServer_Database_Waits_Configuration], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_Enabled] AS [AzureSqlServer_Database_Waits_Enabled], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_AlertNotification] AS [AzureSqlServer_Database_Waits_AlertNotification], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_EmailAddress] AS [AzureSqlServer_Database_Waits_EmailAddress], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_Version] AS [AzureSqlServer_Database_Waits_Version], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_Comments] AS [AzureSqlServer_Database_Waits_Comments], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_SlackEnabled] AS [AzureSqlServer_Database_Waits_SlackEnabled], [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[_SnmpEnabled] AS [AzureSqlServer_Database_Waits_SnmpEnabled], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_Waits_Keys].[_WaitType] AS [AzureSqlServer_Database_Waits_WaitType] FROM [config].[AzureSqlServer_Database_Waits_AlertConfiguration] INNER JOIN [data].[AzureSqlServer_Database_Waits_Keys] ON [data].[AzureSqlServer_Database_Waits_Keys].[Id] = [config].[AzureSqlServer_Database_Waits_AlertConfiguration].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_Waits_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
