SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_ResourceGroup_Resource_AlertConfiguration_View] AS SELECT[config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[Id] AS [Id], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_AlertType] AS [Cluster_ResourceGroup_Resource_AlertType], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_SubType] AS [Cluster_ResourceGroup_Resource_SubType], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_Configuration] AS [Cluster_ResourceGroup_Resource_Configuration], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_Enabled] AS [Cluster_ResourceGroup_Resource_Enabled], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_AlertNotification] AS [Cluster_ResourceGroup_Resource_AlertNotification], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_EmailAddress] AS [Cluster_ResourceGroup_Resource_EmailAddress], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_Version] AS [Cluster_ResourceGroup_Resource_Version], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_Comments] AS [Cluster_ResourceGroup_Resource_Comments], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_SlackEnabled] AS [Cluster_ResourceGroup_Resource_SlackEnabled], [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[_SnmpEnabled] AS [Cluster_ResourceGroup_Resource_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_ResourceGroup_Keys].[_Name] AS [Cluster_ResourceGroup_Name], [data].[Cluster_ResourceGroup_Resource_Keys].[_Name] AS [Cluster_ResourceGroup_Resource_Name] FROM [config].[Cluster_ResourceGroup_Resource_AlertConfiguration] INNER JOIN [data].[Cluster_ResourceGroup_Resource_Keys] ON [data].[Cluster_ResourceGroup_Resource_Keys].[Id] = [config].[Cluster_ResourceGroup_Resource_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_ResourceGroup_Keys] ON [data].[Cluster_ResourceGroup_Keys].[Id] = [data].[Cluster_ResourceGroup_Resource_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_ResourceGroup_Keys].[ParentId]
;
GO
