SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration_View] AS SELECT[config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[Id] AS [Id], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_AlertType] AS [AzureSqlServer_Database_TopQueries_AlertType], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_SubType] AS [AzureSqlServer_Database_TopQueries_SubType], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_Configuration] AS [AzureSqlServer_Database_TopQueries_Configuration], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_Enabled] AS [AzureSqlServer_Database_TopQueries_Enabled], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_AlertNotification] AS [AzureSqlServer_Database_TopQueries_AlertNotification], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_EmailAddress] AS [AzureSqlServer_Database_TopQueries_EmailAddress], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_Version] AS [AzureSqlServer_Database_TopQueries_Version], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_Comments] AS [AzureSqlServer_Database_TopQueries_Comments], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_SlackEnabled] AS [AzureSqlServer_Database_TopQueries_SlackEnabled], [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[_SnmpEnabled] AS [AzureSqlServer_Database_TopQueries_SnmpEnabled], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_TopQueries_Keys].[_DatabaseName] AS [AzureSqlServer_Database_TopQueries_DatabaseName], [data].[AzureSqlServer_Database_TopQueries_Keys].[_SqlHandle] AS [AzureSqlServer_Database_TopQueries_SqlHandle], [data].[AzureSqlServer_Database_TopQueries_Keys].[_StatementEnd] AS [AzureSqlServer_Database_TopQueries_StatementEnd], [data].[AzureSqlServer_Database_TopQueries_Keys].[_StatementStart] AS [AzureSqlServer_Database_TopQueries_StatementStart] FROM [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration] INNER JOIN [data].[AzureSqlServer_Database_TopQueries_Keys] ON [data].[AzureSqlServer_Database_TopQueries_Keys].[Id] = [config].[AzureSqlServer_Database_TopQueries_AlertConfiguration].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_TopQueries_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
