SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Database_Table_Index_AlertType], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Database_Table_Index_SubType], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Database_Table_Index_Configuration], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Database_Table_Index_Enabled], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Database_Table_Index_AlertNotification], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Database_Table_Index_EmailAddress], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Database_Table_Index_Version], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Database_Table_Index_Comments], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Database_Table_Index_SlackEnabled], [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Database_Table_Index_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Database_Keys].[_Name] AS [Cluster_SqlServer_Database_Name], [data].[Cluster_SqlServer_Database_Table_Keys].[_Name] AS [Cluster_SqlServer_Database_Table_Name], [data].[Cluster_SqlServer_Database_Table_Keys].[_Schema] AS [Cluster_SqlServer_Database_Table_Schema], [data].[Cluster_SqlServer_Database_Table_Index_Keys].[_Name] AS [Cluster_SqlServer_Database_Table_Index_Name] FROM [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Database_Table_Index_Keys] ON [data].[Cluster_SqlServer_Database_Table_Index_Keys].[Id] = [config].[Cluster_SqlServer_Database_Table_Index_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Database_Table_Keys] ON [data].[Cluster_SqlServer_Database_Table_Keys].[Id] = [data].[Cluster_SqlServer_Database_Table_Index_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Database_Keys] ON [data].[Cluster_SqlServer_Database_Keys].[Id] = [data].[Cluster_SqlServer_Database_Table_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Database_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
