SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Database_BackupType_Backup_AlertType], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Database_BackupType_Backup_SubType], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Database_BackupType_Backup_Configuration], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Database_BackupType_Backup_Enabled], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Database_BackupType_Backup_AlertNotification], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Database_BackupType_Backup_EmailAddress], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Database_BackupType_Backup_Version], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Database_BackupType_Backup_Comments], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Database_BackupType_Backup_SlackEnabled], [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Database_BackupType_Backup_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Database_Keys].[_Name] AS [Cluster_SqlServer_Database_Name], [data].[Cluster_SqlServer_Database_BackupType_Keys].[_Type] AS [Cluster_SqlServer_Database_BackupType_Type], [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[_StartDate] AS [Cluster_SqlServer_Database_BackupType_Backup_StartDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[_StartDate]) AS [Cluster_SqlServer_Database_BackupType_Backup_StartDate_DateTime] FROM [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys] ON [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[Id] = [config].[Cluster_SqlServer_Database_BackupType_Backup_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Database_BackupType_Keys] ON [data].[Cluster_SqlServer_Database_BackupType_Keys].[Id] = [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Database_Keys] ON [data].[Cluster_SqlServer_Database_Keys].[Id] = [data].[Cluster_SqlServer_Database_BackupType_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Database_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
