SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Error_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Error_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Error_AlertType], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Error_SubType], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Error_Configuration], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Error_Enabled], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Error_AlertNotification], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Error_EmailAddress], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Error_Version], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Error_Comments], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Error_SlackEnabled], [config].[Cluster_SqlServer_Error_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Error_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Error_Keys].[_LogDate] AS [Cluster_SqlServer_Error_LogDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Error_Keys].[_LogDate]) AS [Cluster_SqlServer_Error_LogDate_DateTime], [data].[Cluster_SqlServer_Error_Keys].[_SequenceNumber] AS [Cluster_SqlServer_Error_SequenceNumber] FROM [config].[Cluster_SqlServer_Error_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Error_Keys] ON [data].[Cluster_SqlServer_Error_Keys].[Id] = [config].[Cluster_SqlServer_Error_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Error_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
