SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration_View] AS SELECT[config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[Id] AS [Id], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_AlertType] AS [AzureSqlServer_Database_CustomMetric_AlertType], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_SubType] AS [AzureSqlServer_Database_CustomMetric_SubType], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_Configuration] AS [AzureSqlServer_Database_CustomMetric_Configuration], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_Enabled] AS [AzureSqlServer_Database_CustomMetric_Enabled], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_AlertNotification] AS [AzureSqlServer_Database_CustomMetric_AlertNotification], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_EmailAddress] AS [AzureSqlServer_Database_CustomMetric_EmailAddress], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_Version] AS [AzureSqlServer_Database_CustomMetric_Version], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_Comments] AS [AzureSqlServer_Database_CustomMetric_Comments], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_SlackEnabled] AS [AzureSqlServer_Database_CustomMetric_SlackEnabled], [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[_SnmpEnabled] AS [AzureSqlServer_Database_CustomMetric_SnmpEnabled], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_CustomMetric_Keys].[_MetricId] AS [AzureSqlServer_Database_CustomMetric_MetricId] FROM [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration] INNER JOIN [data].[AzureSqlServer_Database_CustomMetric_Keys] ON [data].[AzureSqlServer_Database_CustomMetric_Keys].[Id] = [config].[AzureSqlServer_Database_CustomMetric_AlertConfiguration].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_CustomMetric_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
