SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Database_File_Projection_AlertType], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Database_File_Projection_SubType], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Database_File_Projection_Configuration], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Database_File_Projection_Enabled], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Database_File_Projection_AlertNotification], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Database_File_Projection_EmailAddress], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Database_File_Projection_Version], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Database_File_Projection_Comments], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Database_File_Projection_SlackEnabled], [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Database_File_Projection_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Database_Keys].[_Name] AS [Cluster_SqlServer_Database_Name], [data].[Cluster_SqlServer_Database_File_Keys].[_Name] AS [Cluster_SqlServer_Database_File_Name], [data].[Cluster_SqlServer_Database_File_Keys].[_Type] AS [Cluster_SqlServer_Database_File_Type] FROM [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Database_File_Keys] ON [data].[Cluster_SqlServer_Database_File_Keys].[Id] = [config].[Cluster_SqlServer_Database_File_Projection_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Database_Keys] ON [data].[Cluster_SqlServer_Database_Keys].[Id] = [data].[Cluster_SqlServer_Database_File_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Database_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
