SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration_View] AS SELECT[config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[Id] AS [Id], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_AlertType] AS [Cluster_AvailabilityGroup_Replica_Database_Status_AlertType], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_SubType] AS [Cluster_AvailabilityGroup_Replica_Database_Status_SubType], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_Configuration] AS [Cluster_AvailabilityGroup_Replica_Database_Status_Configuration], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_Enabled] AS [Cluster_AvailabilityGroup_Replica_Database_Status_Enabled], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_AlertNotification] AS [Cluster_AvailabilityGroup_Replica_Database_Status_AlertNotification], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_EmailAddress] AS [Cluster_AvailabilityGroup_Replica_Database_Status_EmailAddress], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_Version] AS [Cluster_AvailabilityGroup_Replica_Database_Status_Version], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_Comments] AS [Cluster_AvailabilityGroup_Replica_Database_Status_Comments], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_SlackEnabled] AS [Cluster_AvailabilityGroup_Replica_Database_Status_SlackEnabled], [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[_SnmpEnabled] AS [Cluster_AvailabilityGroup_Replica_Database_Status_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_AvailabilityGroup_Keys].[_Name] AS [Cluster_AvailabilityGroup_Name], [data].[Cluster_AvailabilityGroup_Replica_Keys].[_Name] AS [Cluster_AvailabilityGroup_Replica_Name], [data].[Cluster_AvailabilityGroup_Replica_Database_Keys].[_Name] AS [Cluster_AvailabilityGroup_Replica_Database_Name] FROM [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration] INNER JOIN [data].[Cluster_AvailabilityGroup_Replica_Database_Keys] ON [data].[Cluster_AvailabilityGroup_Replica_Database_Keys].[Id] = [config].[Cluster_AvailabilityGroup_Replica_Database_Status_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_AvailabilityGroup_Replica_Keys] ON [data].[Cluster_AvailabilityGroup_Replica_Keys].[Id] = [data].[Cluster_AvailabilityGroup_Replica_Database_Keys].[ParentId]
 INNER JOIN [data].[Cluster_AvailabilityGroup_Keys] ON [data].[Cluster_AvailabilityGroup_Keys].[Id] = [data].[Cluster_AvailabilityGroup_Replica_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_AvailabilityGroup_Keys].[ParentId]
;
GO
