SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration_View] AS SELECT[config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[Id] AS [Id], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_AlertType] AS [Cluster_Machine_LogicalDisk_VolumeLabel_AlertType], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_SubType] AS [Cluster_Machine_LogicalDisk_VolumeLabel_SubType], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_Configuration] AS [Cluster_Machine_LogicalDisk_VolumeLabel_Configuration], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_Enabled] AS [Cluster_Machine_LogicalDisk_VolumeLabel_Enabled], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_AlertNotification] AS [Cluster_Machine_LogicalDisk_VolumeLabel_AlertNotification], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_EmailAddress] AS [Cluster_Machine_LogicalDisk_VolumeLabel_EmailAddress], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_Version] AS [Cluster_Machine_LogicalDisk_VolumeLabel_Version], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_Comments] AS [Cluster_Machine_LogicalDisk_VolumeLabel_Comments], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_SlackEnabled] AS [Cluster_Machine_LogicalDisk_VolumeLabel_SlackEnabled], [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[_SnmpEnabled] AS [Cluster_Machine_LogicalDisk_VolumeLabel_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_Machine_Keys].[_Name] AS [Cluster_Machine_Name], [data].[Cluster_Machine_LogicalDisk_Keys].[_Name] AS [Cluster_Machine_LogicalDisk_Name] FROM [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration] INNER JOIN [data].[Cluster_Machine_LogicalDisk_Keys] ON [data].[Cluster_Machine_LogicalDisk_Keys].[Id] = [config].[Cluster_Machine_LogicalDisk_VolumeLabel_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_Machine_Keys] ON [data].[Cluster_Machine_Keys].[Id] = [data].[Cluster_Machine_LogicalDisk_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_Machine_Keys].[ParentId]
;
GO
