SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Agent_Job_Schedule_AlertType], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Agent_Job_Schedule_SubType], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Agent_Job_Schedule_Configuration], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Agent_Job_Schedule_Enabled], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Agent_Job_Schedule_AlertNotification], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Agent_Job_Schedule_EmailAddress], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Agent_Job_Schedule_Version], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Agent_Job_Schedule_Comments], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Agent_Job_Schedule_SlackEnabled], [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Agent_Job_Schedule_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Agent_Job_Keys].[_Name] AS [Cluster_SqlServer_Agent_Job_Name] FROM [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Agent_Job_Keys] ON [data].[Cluster_SqlServer_Agent_Job_Keys].[Id] = [config].[Cluster_SqlServer_Agent_Job_Schedule_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Agent_Job_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
