SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration_View] AS SELECT[config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[Id] AS [Id], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_AlertType] AS [Cluster_Machine_LogicalDisk_Projection_AlertType], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_SubType] AS [Cluster_Machine_LogicalDisk_Projection_SubType], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_Configuration] AS [Cluster_Machine_LogicalDisk_Projection_Configuration], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_Enabled] AS [Cluster_Machine_LogicalDisk_Projection_Enabled], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_AlertNotification] AS [Cluster_Machine_LogicalDisk_Projection_AlertNotification], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_EmailAddress] AS [Cluster_Machine_LogicalDisk_Projection_EmailAddress], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_Version] AS [Cluster_Machine_LogicalDisk_Projection_Version], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_Comments] AS [Cluster_Machine_LogicalDisk_Projection_Comments], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_SlackEnabled] AS [Cluster_Machine_LogicalDisk_Projection_SlackEnabled], [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[_SnmpEnabled] AS [Cluster_Machine_LogicalDisk_Projection_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_Machine_Keys].[_Name] AS [Cluster_Machine_Name], [data].[Cluster_Machine_LogicalDisk_Keys].[_Name] AS [Cluster_Machine_LogicalDisk_Name] FROM [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration] INNER JOIN [data].[Cluster_Machine_LogicalDisk_Keys] ON [data].[Cluster_Machine_LogicalDisk_Keys].[Id] = [config].[Cluster_Machine_LogicalDisk_Projection_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_Machine_Keys] ON [data].[Cluster_Machine_Keys].[Id] = [data].[Cluster_Machine_LogicalDisk_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_Machine_Keys].[ParentId]
;
GO
