SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration_View] AS SELECT[config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[Id] AS [Id], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_AlertType] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertType], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_SubType] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_SubType], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_Configuration] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_Configuration], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_Enabled] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_Enabled], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_AlertNotification] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertNotification], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_EmailAddress] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_EmailAddress], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_Version] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_Version], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_Comments] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_Comments], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_SlackEnabled] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_SlackEnabled], [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[_SnmpEnabled] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_SnmpEnabled], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_TopQueries_Keys].[_DatabaseName] AS [AzureSqlServer_Database_TopQueries_DatabaseName], [data].[AzureSqlServer_Database_TopQueries_Keys].[_SqlHandle] AS [AzureSqlServer_Database_TopQueries_SqlHandle], [data].[AzureSqlServer_Database_TopQueries_Keys].[_StatementEnd] AS [AzureSqlServer_Database_TopQueries_StatementEnd], [data].[AzureSqlServer_Database_TopQueries_Keys].[_StatementStart] AS [AzureSqlServer_Database_TopQueries_StatementStart], [data].[AzureSqlServer_Database_TopQueries_QueryWaitStats_Keys].[_WaitType] AS [AzureSqlServer_Database_TopQueries_QueryWaitStats_WaitType] FROM [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration] INNER JOIN [data].[AzureSqlServer_Database_TopQueries_QueryWaitStats_Keys] ON [data].[AzureSqlServer_Database_TopQueries_QueryWaitStats_Keys].[Id] = [config].[AzureSqlServer_Database_TopQueries_QueryWaitStats_AlertConfiguration].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_TopQueries_Keys] ON [data].[AzureSqlServer_Database_TopQueries_Keys].[Id] = [data].[AzureSqlServer_Database_TopQueries_QueryWaitStats_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_TopQueries_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
