SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration_View] AS SELECT[config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[Id] AS [Id], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_AlertType] AS [AzureSqlServer_Database_ExtendedEvents_AlertType], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_SubType] AS [AzureSqlServer_Database_ExtendedEvents_SubType], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_Configuration] AS [AzureSqlServer_Database_ExtendedEvents_Configuration], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_Enabled] AS [AzureSqlServer_Database_ExtendedEvents_Enabled], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_AlertNotification] AS [AzureSqlServer_Database_ExtendedEvents_AlertNotification], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_EmailAddress] AS [AzureSqlServer_Database_ExtendedEvents_EmailAddress], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_Version] AS [AzureSqlServer_Database_ExtendedEvents_Version], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_Comments] AS [AzureSqlServer_Database_ExtendedEvents_Comments], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_SlackEnabled] AS [AzureSqlServer_Database_ExtendedEvents_SlackEnabled], [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[_SnmpEnabled] AS [AzureSqlServer_Database_ExtendedEvents_SnmpEnabled], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_EventName] AS [AzureSqlServer_Database_ExtendedEvents_EventName], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_Sequence] AS [AzureSqlServer_Database_ExtendedEvents_Sequence], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_TimeStamp] AS [AzureSqlServer_Database_ExtendedEvents_TimeStamp], [utils].[TicksToDateTime]([data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_TimeStamp]) AS [AzureSqlServer_Database_ExtendedEvents_TimeStamp_DateTime] FROM [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration] INNER JOIN [data].[AzureSqlServer_Database_ExtendedEvents_Keys] ON [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[Id] = [config].[AzureSqlServer_Database_ExtendedEvents_AlertConfiguration].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
