SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration_View] AS SELECT[config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[Id] AS [Id], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_AlertType] AS [AzureSqlServer_Database_QueryPlans_AlertType], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_SubType] AS [AzureSqlServer_Database_QueryPlans_SubType], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_Configuration] AS [AzureSqlServer_Database_QueryPlans_Configuration], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_Enabled] AS [AzureSqlServer_Database_QueryPlans_Enabled], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_AlertNotification] AS [AzureSqlServer_Database_QueryPlans_AlertNotification], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_EmailAddress] AS [AzureSqlServer_Database_QueryPlans_EmailAddress], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_Version] AS [AzureSqlServer_Database_QueryPlans_Version], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_Comments] AS [AzureSqlServer_Database_QueryPlans_Comments], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_SlackEnabled] AS [AzureSqlServer_Database_QueryPlans_SlackEnabled], [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[_SnmpEnabled] AS [AzureSqlServer_Database_QueryPlans_SnmpEnabled], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_QueryPlans_Keys].[_PlanHandle] AS [AzureSqlServer_Database_QueryPlans_PlanHandle] FROM [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration] INNER JOIN [data].[AzureSqlServer_Database_QueryPlans_Keys] ON [data].[AzureSqlServer_Database_QueryPlans_Keys].[Id] = [config].[AzureSqlServer_Database_QueryPlans_AlertConfiguration].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_QueryPlans_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
