SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Agent_Job_History_AlertType], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Agent_Job_History_SubType], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Agent_Job_History_Configuration], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Agent_Job_History_Enabled], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Agent_Job_History_AlertNotification], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Agent_Job_History_EmailAddress], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Agent_Job_History_Version], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Agent_Job_History_Comments], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Agent_Job_History_SlackEnabled], [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Agent_Job_History_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Agent_Job_Keys].[_Name] AS [Cluster_SqlServer_Agent_Job_Name], [data].[Cluster_SqlServer_Agent_Job_History_Keys].[_Id] AS [Cluster_SqlServer_Agent_Job_History_Id], [data].[Cluster_SqlServer_Agent_Job_History_Keys].[_RunDate] AS [Cluster_SqlServer_Agent_Job_History_RunDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Agent_Job_History_Keys].[_RunDate]) AS [Cluster_SqlServer_Agent_Job_History_RunDate_DateTime] FROM [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Agent_Job_History_Keys] ON [data].[Cluster_SqlServer_Agent_Job_History_Keys].[Id] = [config].[Cluster_SqlServer_Agent_Job_History_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Agent_Job_Keys] ON [data].[Cluster_SqlServer_Agent_Job_Keys].[Id] = [data].[Cluster_SqlServer_Agent_Job_History_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Agent_Job_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
