SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [config].[Cluster_SqlServer_Trace_AlertConfiguration_View] AS SELECT[config].[Cluster_SqlServer_Trace_AlertConfiguration].[Id] AS [Id], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_AlertType] AS [Cluster_SqlServer_Trace_AlertType], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_SubType] AS [Cluster_SqlServer_Trace_SubType], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_Configuration] AS [Cluster_SqlServer_Trace_Configuration], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_Enabled] AS [Cluster_SqlServer_Trace_Enabled], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_AlertNotification] AS [Cluster_SqlServer_Trace_AlertNotification], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_EmailAddress] AS [Cluster_SqlServer_Trace_EmailAddress], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_Version] AS [Cluster_SqlServer_Trace_Version], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_Comments] AS [Cluster_SqlServer_Trace_Comments], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_SlackEnabled] AS [Cluster_SqlServer_Trace_SlackEnabled], [config].[Cluster_SqlServer_Trace_AlertConfiguration].[_SnmpEnabled] AS [Cluster_SqlServer_Trace_SnmpEnabled], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Trace_Keys].[_SequenceNumber] AS [Cluster_SqlServer_Trace_SequenceNumber], [data].[Cluster_SqlServer_Trace_Keys].[_StartTime] AS [Cluster_SqlServer_Trace_StartTime], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Trace_Keys].[_StartTime]) AS [Cluster_SqlServer_Trace_StartTime_DateTime] FROM [config].[Cluster_SqlServer_Trace_AlertConfiguration] INNER JOIN [data].[Cluster_SqlServer_Trace_Keys] ON [data].[Cluster_SqlServer_Trace_Keys].[Id] = [config].[Cluster_SqlServer_Trace_AlertConfiguration].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Trace_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
