SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [data].[Cluster_SqlServer_Database_StableSamples_View] AS SELECT[data].[Cluster_SqlServer_Database_StableSamples].[Id] AS [Id], [data].[Cluster_SqlServer_Database_Keys].[CollectionDate] AS [IdCollectionDate], [data].[Cluster_SqlServer_Database_StableSamples].[_AutoCreateStatistics] AS [Cluster_SqlServer_Database_AutoCreateStatistics], [data].[Cluster_SqlServer_Database_StableSamples].[_AutoShrink] AS [Cluster_SqlServer_Database_AutoShrink], [data].[Cluster_SqlServer_Database_StableSamples].[_Collation] AS [Cluster_SqlServer_Database_Collation], [data].[Cluster_SqlServer_Database_StableSamples].[_CompatibilityLevel] AS [Cluster_SqlServer_Database_CompatibilityLevel], [data].[Cluster_SqlServer_Database_StableSamples].[_CreateDate] AS [Cluster_SqlServer_Database_CreateDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Database_StableSamples].[_CreateDate]) AS [Cluster_SqlServer_Database_CreateDate_DateTime], [data].[Cluster_SqlServer_Database_StableSamples].[_DatabaseId] AS [Cluster_SqlServer_Database_DatabaseId], [data].[Cluster_SqlServer_Database_StableSamples].[_PageVerify] AS [Cluster_SqlServer_Database_PageVerify], [data].[Cluster_SqlServer_Database_StableSamples].[_ReadOnly] AS [Cluster_SqlServer_Database_ReadOnly], [data].[Cluster_SqlServer_Database_StableSamples].[_RecoveryModel] AS [Cluster_SqlServer_Database_RecoveryModel], [data].[Cluster_SqlServer_Database_StableSamples].[_Standby] AS [Cluster_SqlServer_Database_Standby], [data].[Cluster_SqlServer_Database_StableSamples].[_State] AS [Cluster_SqlServer_Database_State], [data].[Cluster_SqlServer_Database_StableSamples].[CollectionDate] AS [CollectionDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Database_StableSamples].[CollectionDate]) AS [CollectionDate_DateTime], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Database_Keys].[_Name] AS [Cluster_SqlServer_Database_Name] FROM [data].[Cluster_SqlServer_Database_StableSamples] INNER JOIN [data].[Cluster_SqlServer_Database_Keys] ON [data].[Cluster_SqlServer_Database_Keys].[Id] = [data].[Cluster_SqlServer_Database_StableSamples].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Database_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
