SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [data].[AzureSqlServer_Database_ExtendedEvents_Instances_View] AS SELECT[data].[AzureSqlServer_Database_ExtendedEvents_Instances].[Id] AS [Id], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[CollectionDate] AS [IdCollectionDate], [data].[AzureSqlServer_Database_ExtendedEvents_Instances].[_EventData] AS [AzureSqlServer_Database_ExtendedEvents_EventData], [data].[AzureSqlServer_Database_ExtendedEvents_Instances].[_FileName] AS [AzureSqlServer_Database_ExtendedEvents_FileName], [data].[AzureSqlServer_Database_ExtendedEvents_Instances].[_FileOffset] AS [AzureSqlServer_Database_ExtendedEvents_FileOffset], [data].[AzureSqlServer_Database_ExtendedEvents_Instances].[CollectionDate] AS [CollectionDate], [utils].[TicksToDateTime]([data].[AzureSqlServer_Database_ExtendedEvents_Instances].[CollectionDate]) AS [CollectionDate_DateTime], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_EventName] AS [AzureSqlServer_Database_ExtendedEvents_EventName], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_Sequence] AS [AzureSqlServer_Database_ExtendedEvents_Sequence], [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_TimeStamp] AS [AzureSqlServer_Database_ExtendedEvents_TimeStamp], [utils].[TicksToDateTime]([data].[AzureSqlServer_Database_ExtendedEvents_Keys].[_TimeStamp]) AS [AzureSqlServer_Database_ExtendedEvents_TimeStamp_DateTime] FROM [data].[AzureSqlServer_Database_ExtendedEvents_Instances] INNER JOIN [data].[AzureSqlServer_Database_ExtendedEvents_Keys] ON [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[Id] = [data].[AzureSqlServer_Database_ExtendedEvents_Instances].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_ExtendedEvents_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
