SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [data].[Cluster_SqlServer_Trace_Instances_View] AS SELECT[data].[Cluster_SqlServer_Trace_Instances].[Id] AS [Id], [data].[Cluster_SqlServer_Trace_Keys].[CollectionDate] AS [IdCollectionDate], [data].[Cluster_SqlServer_Trace_Instances].[_ApplicationName] AS [Cluster_SqlServer_Trace_ApplicationName], [data].[Cluster_SqlServer_Trace_Instances].[_DatabaseName] AS [Cluster_SqlServer_Trace_DatabaseName], [data].[Cluster_SqlServer_Trace_Instances].[_HostName] AS [Cluster_SqlServer_Trace_HostName], [data].[Cluster_SqlServer_Trace_Instances].[_LoginName] AS [Cluster_SqlServer_Trace_LoginName], [data].[Cluster_SqlServer_Trace_Instances].[_Spid] AS [Cluster_SqlServer_Trace_Spid], [data].[Cluster_SqlServer_Trace_Instances].[_TextData] AS [Cluster_SqlServer_Trace_TextData], [data].[Cluster_SqlServer_Trace_Instances].[CollectionDate] AS [CollectionDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Trace_Instances].[CollectionDate]) AS [CollectionDate_DateTime], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Trace_Keys].[_SequenceNumber] AS [Cluster_SqlServer_Trace_SequenceNumber], [data].[Cluster_SqlServer_Trace_Keys].[_StartTime] AS [Cluster_SqlServer_Trace_StartTime], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Trace_Keys].[_StartTime]) AS [Cluster_SqlServer_Trace_StartTime_DateTime] FROM [data].[Cluster_SqlServer_Trace_Instances] INNER JOIN [data].[Cluster_SqlServer_Trace_Keys] ON [data].[Cluster_SqlServer_Trace_Keys].[Id] = [data].[Cluster_SqlServer_Trace_Instances].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Trace_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
