SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [data].[AzureSqlServer_Database_TopQueries_UnstableSamples_View] AS SELECT[data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[Id] AS [Id], [data].[AzureSqlServer_Database_TopQueries_Keys].[CollectionDate] AS [IdCollectionDate], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[_ExecutionCount] AS [AzureSqlServer_Database_TopQueries_ExecutionCount], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[_ExecutionTime] AS [AzureSqlServer_Database_TopQueries_ExecutionTime], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[_LogicalReads] AS [AzureSqlServer_Database_TopQueries_LogicalReads], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[_LogicalWrites] AS [AzureSqlServer_Database_TopQueries_LogicalWrites], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[_PhysicalReads] AS [AzureSqlServer_Database_TopQueries_PhysicalReads], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[_WorkerTime] AS [AzureSqlServer_Database_TopQueries_WorkerTime], [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[CollectionDate] AS [CollectionDate], [utils].[TicksToDateTime]([data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[CollectionDate]) AS [CollectionDate_DateTime], [data].[AzureSqlServer_Keys].[_Name] AS [AzureSqlServer_Name], [data].[AzureSqlServer_Database_Keys].[_Name] AS [AzureSqlServer_Database_Name], [data].[AzureSqlServer_Database_TopQueries_Keys].[_DatabaseName] AS [AzureSqlServer_Database_TopQueries_DatabaseName], [data].[AzureSqlServer_Database_TopQueries_Keys].[_SqlHandle] AS [AzureSqlServer_Database_TopQueries_SqlHandle], [data].[AzureSqlServer_Database_TopQueries_Keys].[_StatementEnd] AS [AzureSqlServer_Database_TopQueries_StatementEnd], [data].[AzureSqlServer_Database_TopQueries_Keys].[_StatementStart] AS [AzureSqlServer_Database_TopQueries_StatementStart] FROM [data].[AzureSqlServer_Database_TopQueries_UnstableSamples] INNER JOIN [data].[AzureSqlServer_Database_TopQueries_Keys] ON [data].[AzureSqlServer_Database_TopQueries_Keys].[Id] = [data].[AzureSqlServer_Database_TopQueries_UnstableSamples].[Id]
 INNER JOIN [data].[AzureSqlServer_Database_Keys] ON [data].[AzureSqlServer_Database_Keys].[Id] = [data].[AzureSqlServer_Database_TopQueries_Keys].[ParentId]
 INNER JOIN [data].[AzureSqlServer_Keys] ON [data].[AzureSqlServer_Keys].[Id] = [data].[AzureSqlServer_Database_Keys].[ParentId]
;
GO
