SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances_View] AS SELECT[data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[Id] AS [Id], [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[CollectionDate] AS [IdCollectionDate], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_BackupDevice] AS [Cluster_SqlServer_Database_BackupType_Backup_BackupDevice], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_BackupSize] AS [Cluster_SqlServer_Database_BackupType_Backup_BackupSize], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_DeviceName] AS [Cluster_SqlServer_Database_BackupType_Backup_DeviceName], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_FinishDate] AS [Cluster_SqlServer_Database_BackupType_Backup_FinishDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_FinishDate]) AS [Cluster_SqlServer_Database_BackupType_Backup_FinishDate_DateTime], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_IsCompressed] AS [Cluster_SqlServer_Database_BackupType_Backup_IsCompressed], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_IsCopyOnly] AS [Cluster_SqlServer_Database_BackupType_Backup_IsCopyOnly], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_IsEncrypted] AS [Cluster_SqlServer_Database_BackupType_Backup_IsEncrypted], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_IsNativeBackup] AS [Cluster_SqlServer_Database_BackupType_Backup_IsNativeBackup], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[_IsPasswordProtected] AS [Cluster_SqlServer_Database_BackupType_Backup_IsPasswordProtected], [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[CollectionDate] AS [CollectionDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[CollectionDate]) AS [CollectionDate_DateTime], [data].[Cluster_Keys].[_Name] AS [Cluster_Name], [data].[Cluster_SqlServer_Keys].[_Name] AS [Cluster_SqlServer_Name], [data].[Cluster_SqlServer_Database_Keys].[_Name] AS [Cluster_SqlServer_Database_Name], [data].[Cluster_SqlServer_Database_BackupType_Keys].[_Type] AS [Cluster_SqlServer_Database_BackupType_Type], [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[_StartDate] AS [Cluster_SqlServer_Database_BackupType_Backup_StartDate], [utils].[TicksToDateTime]([data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[_StartDate]) AS [Cluster_SqlServer_Database_BackupType_Backup_StartDate_DateTime] FROM [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances] INNER JOIN [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys] ON [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[Id] = [data].[Cluster_SqlServer_Database_BackupType_Backup_Instances].[Id]
 INNER JOIN [data].[Cluster_SqlServer_Database_BackupType_Keys] ON [data].[Cluster_SqlServer_Database_BackupType_Keys].[Id] = [data].[Cluster_SqlServer_Database_BackupType_Backup_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Database_Keys] ON [data].[Cluster_SqlServer_Database_Keys].[Id] = [data].[Cluster_SqlServer_Database_BackupType_Keys].[ParentId]
 INNER JOIN [data].[Cluster_SqlServer_Keys] ON [data].[Cluster_SqlServer_Keys].[Id] = [data].[Cluster_SqlServer_Database_Keys].[ParentId]
 INNER JOIN [data].[Cluster_Keys] ON [data].[Cluster_Keys].[Id] = [data].[Cluster_SqlServer_Keys].[ParentId]
;
GO
